//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductoServiceTest.ProductosWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/ProductoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/ProductoServices.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo1 {
            get {
                return this.Codigo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo1Field, value) != true)) {
                    this.Codigo1Field = value;
                    this.RaisePropertyChanged("Codigo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductosWS.IProductos")]
    public interface IProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/CrearProducto", ReplyAction="http://tempuri.org/IProductos/CrearProductoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductoServiceTest.ProductosWS.RepetidoException), Action="http://tempuri.org/IProductos/CrearProductoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/ProductoServices.Errores")]
        ProductoServiceTest.ProductosWS.Producto CrearProducto(ProductoServiceTest.ProductosWS.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/CrearProducto", ReplyAction="http://tempuri.org/IProductos/CrearProductoResponse")]
        System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto> CrearProductoAsync(ProductoServiceTest.ProductosWS.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        ProductoServiceTest.ProductosWS.Producto ObtenerProducto(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto> ObtenerProductoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ModificarProducto", ReplyAction="http://tempuri.org/IProductos/ModificarProductoResponse")]
        ProductoServiceTest.ProductosWS.Producto ModificarProducto(ProductoServiceTest.ProductosWS.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ModificarProducto", ReplyAction="http://tempuri.org/IProductos/ModificarProductoResponse")]
        System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto> ModificarProductoAsync(ProductoServiceTest.ProductosWS.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/EliminarProducto", ReplyAction="http://tempuri.org/IProductos/EliminarProductoResponse")]
        void EliminarProducto(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/EliminarProducto", ReplyAction="http://tempuri.org/IProductos/EliminarProductoResponse")]
        System.Threading.Tasks.Task EliminarProductoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        ProductoServiceTest.ProductosWS.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto[]> ListarProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosChannel : ProductoServiceTest.ProductosWS.IProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.ClientBase<ProductoServiceTest.ProductosWS.IProductos>, ProductoServiceTest.ProductosWS.IProductos {
        
        public ProductosClient() {
        }
        
        public ProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProductoServiceTest.ProductosWS.Producto CrearProducto(ProductoServiceTest.ProductosWS.Producto productoACrear) {
            return base.Channel.CrearProducto(productoACrear);
        }
        
        public System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto> CrearProductoAsync(ProductoServiceTest.ProductosWS.Producto productoACrear) {
            return base.Channel.CrearProductoAsync(productoACrear);
        }
        
        public ProductoServiceTest.ProductosWS.Producto ObtenerProducto(int codigo) {
            return base.Channel.ObtenerProducto(codigo);
        }
        
        public System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto> ObtenerProductoAsync(int codigo) {
            return base.Channel.ObtenerProductoAsync(codigo);
        }
        
        public ProductoServiceTest.ProductosWS.Producto ModificarProducto(ProductoServiceTest.ProductosWS.Producto productoAModificar) {
            return base.Channel.ModificarProducto(productoAModificar);
        }
        
        public System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto> ModificarProductoAsync(ProductoServiceTest.ProductosWS.Producto productoAModificar) {
            return base.Channel.ModificarProductoAsync(productoAModificar);
        }
        
        public void EliminarProducto(int codigo) {
            base.Channel.EliminarProducto(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarProductoAsync(int codigo) {
            return base.Channel.EliminarProductoAsync(codigo);
        }
        
        public ProductoServiceTest.ProductosWS.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<ProductoServiceTest.ProductosWS.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
    }
}
